# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'const_dialog.ui'
#
# Created: Thu Apr  7 11:21:29 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(406, 243)
        self.time = QtGui.QDoubleSpinBox(Dialog)
        self.time.setGeometry(QtCore.QRect(165, 31, 80, 20))
        self.time.setMinimum(-99999999.0)
        self.time.setMaximum(99999999.0)
        self.time.setSingleStep(0.01)
        self.time.setObjectName(_fromUtf8("time"))
        self.timelLabel = QtGui.QLabel(Dialog)
        self.timelLabel.setGeometry(QtCore.QRect(42, 32, 60, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.timelLabel.setFont(font)
        self.timelLabel.setObjectName(_fromUtf8("timelLabel"))
        self.timelLabel_2 = QtGui.QLabel(Dialog)
        self.timelLabel_2.setGeometry(QtCore.QRect(42, 71, 100, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.timelLabel_2.setFont(font)
        self.timelLabel_2.setObjectName(_fromUtf8("timelLabel_2"))
        self.integrStep = QtGui.QDoubleSpinBox(Dialog)
        self.integrStep.setGeometry(QtCore.QRect(165, 70, 80, 20))
        self.integrStep.setDecimals(4)
        self.integrStep.setMinimum(-99999999.0)
        self.integrStep.setMaximum(99999999.0)
        self.integrStep.setSingleStep(0.01)
        self.integrStep.setObjectName(_fromUtf8("integrStep"))
        self.scaleX = QtGui.QDoubleSpinBox(Dialog)
        self.scaleX.setGeometry(QtCore.QRect(165, 150, 80, 20))
        self.scaleX.setDecimals(5)
        self.scaleX.setMinimum(-99999999.0)
        self.scaleX.setMaximum(99999999.0)
        self.scaleX.setSingleStep(0.01)
        self.scaleX.setProperty(_fromUtf8("value"), 1.0)
        self.scaleX.setObjectName(_fromUtf8("scaleX"))
        self.scaleYLabel = QtGui.QLabel(Dialog)
        self.scaleYLabel.setGeometry(QtCore.QRect(250, 152, 16, 16))
        self.scaleYLabel.setObjectName(_fromUtf8("scaleYLabel"))
        self.scaleXLabel = QtGui.QLabel(Dialog)
        self.scaleXLabel.setGeometry(QtCore.QRect(152, 152, 16, 16))
        self.scaleXLabel.setObjectName(_fromUtf8("scaleXLabel"))
        self.scaleLabel = QtGui.QLabel(Dialog)
        self.scaleLabel.setGeometry(QtCore.QRect(43, 151, 80, 15))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.scaleLabel.setFont(font)
        self.scaleLabel.setObjectName(_fromUtf8("scaleLabel"))
        self.parameterK = QtGui.QDoubleSpinBox(Dialog)
        self.parameterK.setGeometry(QtCore.QRect(262, 107, 80, 20))
        self.parameterK.setDecimals(4)
        self.parameterK.setMinimum(-99999999.0)
        self.parameterK.setMaximum(99999999.0)
        self.parameterK.setSingleStep(0.01)
        self.parameterK.setObjectName(_fromUtf8("parameterK"))
        self.parameterM = QtGui.QDoubleSpinBox(Dialog)
        self.parameterM.setGeometry(QtCore.QRect(165, 107, 80, 20))
        self.parameterM.setDecimals(4)
        self.parameterM.setMinimum(-99999999.0)
        self.parameterM.setMaximum(99999999.0)
        self.parameterM.setSingleStep(0.01)
        self.parameterM.setObjectName(_fromUtf8("parameterM"))
        self.scaleY = QtGui.QDoubleSpinBox(Dialog)
        self.scaleY.setGeometry(QtCore.QRect(263, 150, 80, 20))
        self.scaleY.setDecimals(5)
        self.scaleY.setMinimum(-99999999.0)
        self.scaleY.setMaximum(99999999.0)
        self.scaleY.setSingleStep(0.01)
        self.scaleY.setProperty(_fromUtf8("value"), 1.0)
        self.scaleY.setObjectName(_fromUtf8("scaleY"))
        self.scaleLabel_2 = QtGui.QLabel(Dialog)
        self.scaleLabel_2.setGeometry(QtCore.QRect(43, 110, 100, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.scaleLabel_2.setFont(font)
        self.scaleLabel_2.setObjectName(_fromUtf8("scaleLabel_2"))
        self.scaleXLabel_2 = QtGui.QLabel(Dialog)
        self.scaleXLabel_2.setGeometry(QtCore.QRect(149, 110, 16, 16))
        self.scaleXLabel_2.setObjectName(_fromUtf8("scaleXLabel_2"))
        self.scaleXLabel_3 = QtGui.QLabel(Dialog)
        self.scaleXLabel_3.setGeometry(QtCore.QRect(250, 110, 20, 16))
        self.scaleXLabel_3.setObjectName(_fromUtf8("scaleXLabel_3"))
        self.applyButton = QtGui.QPushButton(Dialog)
        self.applyButton.setGeometry(QtCore.QRect(20, 200, 85, 27))
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.resetButton = QtGui.QPushButton(Dialog)
        self.resetButton.setGeometry(QtCore.QRect(110, 200, 85, 27))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Редактирование констант", None, QtGui.QApplication.UnicodeUTF8))
        self.timelLabel.setText(QtGui.QApplication.translate("Dialog", "Время:", None, QtGui.QApplication.UnicodeUTF8))
        self.timelLabel_2.setText(QtGui.QApplication.translate("Dialog", "Шаг интгр-я:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleYLabel.setText(QtGui.QApplication.translate("Dialog", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleXLabel.setText(QtGui.QApplication.translate("Dialog", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel.setText(QtGui.QApplication.translate("Dialog", "Масштаб:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel_2.setText(QtGui.QApplication.translate("Dialog", "Параметры:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleXLabel_2.setText(QtGui.QApplication.translate("Dialog", "m:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleXLabel_3.setText(QtGui.QApplication.translate("Dialog", "k:", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("Dialog", "Применить", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("Dialog", "Сброс", None, QtGui.QApplication.UnicodeUTF8))

