# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'const_dialog.ui'
#
# Created: Wed May 11 23:19:04 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(611, 456)
        self.time = QtGui.QDoubleSpinBox(Dialog)
        self.time.setGeometry(QtCore.QRect(165, 31, 80, 20))
        self.time.setMinimum(-99999999.0)
        self.time.setMaximum(99999999.0)
        self.time.setSingleStep(0.01)
        self.time.setObjectName(_fromUtf8("time"))
        self.timelLabel = QtGui.QLabel(Dialog)
        self.timelLabel.setGeometry(QtCore.QRect(42, 32, 60, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.timelLabel.setFont(font)
        self.timelLabel.setObjectName(_fromUtf8("timelLabel"))
        self.timelLabel_2 = QtGui.QLabel(Dialog)
        self.timelLabel_2.setGeometry(QtCore.QRect(42, 71, 100, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.timelLabel_2.setFont(font)
        self.timelLabel_2.setObjectName(_fromUtf8("timelLabel_2"))
        self.integrStep = QtGui.QDoubleSpinBox(Dialog)
        self.integrStep.setGeometry(QtCore.QRect(165, 70, 80, 20))
        self.integrStep.setDecimals(4)
        self.integrStep.setMinimum(-99999999.0)
        self.integrStep.setMaximum(99999999.0)
        self.integrStep.setSingleStep(0.01)
        self.integrStep.setObjectName(_fromUtf8("integrStep"))
        self.scaleX = QtGui.QDoubleSpinBox(Dialog)
        self.scaleX.setGeometry(QtCore.QRect(165, 150, 80, 20))
        self.scaleX.setDecimals(5)
        self.scaleX.setMinimum(-99999999.0)
        self.scaleX.setMaximum(99999999.0)
        self.scaleX.setSingleStep(0.01)
        self.scaleX.setProperty(_fromUtf8("value"), 1.0)
        self.scaleX.setObjectName(_fromUtf8("scaleX"))
        self.scaleYLabel = QtGui.QLabel(Dialog)
        self.scaleYLabel.setGeometry(QtCore.QRect(250, 152, 16, 16))
        self.scaleYLabel.setObjectName(_fromUtf8("scaleYLabel"))
        self.scaleXLabel = QtGui.QLabel(Dialog)
        self.scaleXLabel.setGeometry(QtCore.QRect(152, 152, 16, 16))
        self.scaleXLabel.setObjectName(_fromUtf8("scaleXLabel"))
        self.scaleLabel = QtGui.QLabel(Dialog)
        self.scaleLabel.setGeometry(QtCore.QRect(43, 151, 80, 15))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.scaleLabel.setFont(font)
        self.scaleLabel.setObjectName(_fromUtf8("scaleLabel"))
        self.parameterK = QtGui.QDoubleSpinBox(Dialog)
        self.parameterK.setGeometry(QtCore.QRect(279, 107, 80, 20))
        self.parameterK.setDecimals(4)
        self.parameterK.setMinimum(-99999999.0)
        self.parameterK.setMaximum(99999999.0)
        self.parameterK.setSingleStep(0.01)
        self.parameterK.setObjectName(_fromUtf8("parameterK"))
        self.parameterM = QtGui.QDoubleSpinBox(Dialog)
        self.parameterM.setGeometry(QtCore.QRect(165, 107, 80, 20))
        self.parameterM.setDecimals(4)
        self.parameterM.setMinimum(-99999999.0)
        self.parameterM.setMaximum(99999999.0)
        self.parameterM.setSingleStep(0.01)
        self.parameterM.setObjectName(_fromUtf8("parameterM"))
        self.scaleY = QtGui.QDoubleSpinBox(Dialog)
        self.scaleY.setGeometry(QtCore.QRect(263, 150, 80, 20))
        self.scaleY.setDecimals(5)
        self.scaleY.setMinimum(-99999999.0)
        self.scaleY.setMaximum(99999999.0)
        self.scaleY.setSingleStep(0.01)
        self.scaleY.setProperty(_fromUtf8("value"), 1.0)
        self.scaleY.setObjectName(_fromUtf8("scaleY"))
        self.scaleLabel_2 = QtGui.QLabel(Dialog)
        self.scaleLabel_2.setGeometry(QtCore.QRect(43, 110, 100, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.scaleLabel_2.setFont(font)
        self.scaleLabel_2.setObjectName(_fromUtf8("scaleLabel_2"))
        self.mLabel = QtGui.QLabel(Dialog)
        self.mLabel.setGeometry(QtCore.QRect(149, 110, 16, 16))
        self.mLabel.setObjectName(_fromUtf8("mLabel"))
        self.kLabel = QtGui.QLabel(Dialog)
        self.kLabel.setGeometry(QtCore.QRect(267, 110, 20, 16))
        self.kLabel.setObjectName(_fromUtf8("kLabel"))
        self.applyButton = QtGui.QPushButton(Dialog)
        self.applyButton.setGeometry(QtCore.QRect(20, 420, 85, 27))
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.resetButton = QtGui.QPushButton(Dialog)
        self.resetButton.setGeometry(QtCore.QRect(110, 420, 85, 27))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.scaleLabel_3 = QtGui.QLabel(Dialog)
        self.scaleLabel_3.setGeometry(QtCore.QRect(43, 232, 120, 15))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.scaleLabel_3.setFont(font)
        self.scaleLabel_3.setObjectName(_fromUtf8("scaleLabel_3"))
        self.showGrid = QtGui.QCheckBox(Dialog)
        self.showGrid.setGeometry(QtCore.QRect(163, 230, 51, 22))
        self.showGrid.setText(_fromUtf8(""))
        self.showGrid.setChecked(True)
        self.showGrid.setObjectName(_fromUtf8("showGrid"))
        self.canonical_t_x = QtGui.QCheckBox(Dialog)
        self.canonical_t_x.setGeometry(QtCore.QRect(290, 290, 50, 22))
        self.canonical_t_x.setShortcut(_fromUtf8(""))
        self.canonical_t_x.setChecked(True)
        self.canonical_t_x.setAutoRepeat(False)
        self.canonical_t_x.setAutoExclusive(False)
        self.canonical_t_x.setObjectName(_fromUtf8("canonical_t_x"))
        self.canonical_t_v = QtGui.QCheckBox(Dialog)
        self.canonical_t_v.setGeometry(QtCore.QRect(290, 320, 50, 22))
        self.canonical_t_v.setShortcut(_fromUtf8(""))
        self.canonical_t_v.setChecked(True)
        self.canonical_t_v.setAutoRepeat(False)
        self.canonical_t_v.setAutoExclusive(False)
        self.canonical_t_v.setObjectName(_fromUtf8("canonical_t_v"))
        self.canonical_t_dh = QtGui.QCheckBox(Dialog)
        self.canonical_t_dh.setGeometry(QtCore.QRect(290, 380, 60, 22))
        self.canonical_t_dh.setShortcut(_fromUtf8(""))
        self.canonical_t_dh.setChecked(True)
        self.canonical_t_dh.setAutoRepeat(False)
        self.canonical_t_dh.setAutoExclusive(False)
        self.canonical_t_dh.setObjectName(_fromUtf8("canonical_t_dh"))
        self.eiler_t_dh = QtGui.QCheckBox(Dialog)
        self.eiler_t_dh.setGeometry(QtCore.QRect(460, 380, 60, 22))
        self.eiler_t_dh.setShortcut(_fromUtf8(""))
        self.eiler_t_dh.setChecked(True)
        self.eiler_t_dh.setAutoRepeat(False)
        self.eiler_t_dh.setAutoExclusive(False)
        self.eiler_t_dh.setObjectName(_fromUtf8("eiler_t_dh"))
        self.eiler_t_x = QtGui.QCheckBox(Dialog)
        self.eiler_t_x.setGeometry(QtCore.QRect(460, 290, 50, 22))
        self.eiler_t_x.setShortcut(_fromUtf8(""))
        self.eiler_t_x.setChecked(True)
        self.eiler_t_x.setAutoRepeat(False)
        self.eiler_t_x.setAutoExclusive(False)
        self.eiler_t_x.setObjectName(_fromUtf8("eiler_t_x"))
        self.eiler_t_v = QtGui.QCheckBox(Dialog)
        self.eiler_t_v.setGeometry(QtCore.QRect(460, 320, 50, 22))
        self.eiler_t_v.setShortcut(_fromUtf8(""))
        self.eiler_t_v.setChecked(True)
        self.eiler_t_v.setAutoRepeat(False)
        self.eiler_t_v.setAutoExclusive(False)
        self.eiler_t_v.setObjectName(_fromUtf8("eiler_t_v"))
        self.eiler_x_v = QtGui.QCheckBox(Dialog)
        self.eiler_x_v.setGeometry(QtCore.QRect(460, 350, 50, 22))
        self.eiler_x_v.setShortcut(_fromUtf8(""))
        self.eiler_x_v.setChecked(True)
        self.eiler_x_v.setAutoRepeat(False)
        self.eiler_x_v.setAutoExclusive(False)
        self.eiler_x_v.setObjectName(_fromUtf8("eiler_x_v"))
        self.canonical_x_v = QtGui.QCheckBox(Dialog)
        self.canonical_x_v.setGeometry(QtCore.QRect(290, 350, 50, 22))
        self.canonical_x_v.setShortcut(_fromUtf8(""))
        self.canonical_x_v.setChecked(True)
        self.canonical_x_v.setAutoRepeat(False)
        self.canonical_x_v.setAutoExclusive(False)
        self.canonical_x_v.setObjectName(_fromUtf8("canonical_x_v"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(270, 270, 101, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(440, 270, 110, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.drawTypeGroup = QtGui.QGroupBox(Dialog)
        self.drawTypeGroup.setGeometry(QtCore.QRect(42, 190, 311, 21))
        self.drawTypeGroup.setObjectName(_fromUtf8("drawTypeGroup"))
        self.lineTypeButton = QtGui.QRadioButton(self.drawTypeGroup)
        self.lineTypeButton.setGeometry(QtCore.QRect(230, 0, 80, 22))
        self.lineTypeButton.setChecked(False)
        self.lineTypeButton.setObjectName(_fromUtf8("lineTypeButton"))
        self.pointTypeButton = QtGui.QRadioButton(self.drawTypeGroup)
        self.pointTypeButton.setGeometry(QtCore.QRect(160, 0, 70, 22))
        self.pointTypeButton.setChecked(True)
        self.pointTypeButton.setObjectName(_fromUtf8("pointTypeButton"))
        self.xLabel = QtGui.QLabel(Dialog)
        self.xLabel.setGeometry(QtCore.QRect(380, 110, 20, 16))
        self.xLabel.setObjectName(_fromUtf8("xLabel"))
        self.parameterX = QtGui.QDoubleSpinBox(Dialog)
        self.parameterX.setGeometry(QtCore.QRect(392, 107, 80, 20))
        self.parameterX.setDecimals(4)
        self.parameterX.setMinimum(-99999999.0)
        self.parameterX.setMaximum(99999999.0)
        self.parameterX.setSingleStep(0.01)
        self.parameterX.setObjectName(_fromUtf8("parameterX"))
        self.parameterV = QtGui.QDoubleSpinBox(Dialog)
        self.parameterV.setGeometry(QtCore.QRect(505, 107, 80, 20))
        self.parameterV.setDecimals(4)
        self.parameterV.setMinimum(-99999999.0)
        self.parameterV.setMaximum(99999999.0)
        self.parameterV.setSingleStep(0.01)
        self.parameterV.setObjectName(_fromUtf8("parameterV"))
        self.xLabel_2 = QtGui.QLabel(Dialog)
        self.xLabel_2.setGeometry(QtCore.QRect(493, 110, 20, 16))
        self.xLabel_2.setObjectName(_fromUtf8("xLabel_2"))
        self.exact_t_h = QtGui.QCheckBox(Dialog)
        self.exact_t_h.setGeometry(QtCore.QRect(110, 380, 60, 22))
        self.exact_t_h.setShortcut(_fromUtf8(""))
        self.exact_t_h.setChecked(True)
        self.exact_t_h.setAutoRepeat(False)
        self.exact_t_h.setAutoExclusive(False)
        self.exact_t_h.setObjectName(_fromUtf8("exact_t_h"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 270, 120, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.exact_x_v = QtGui.QCheckBox(Dialog)
        self.exact_x_v.setGeometry(QtCore.QRect(110, 350, 50, 22))
        self.exact_x_v.setShortcut(_fromUtf8(""))
        self.exact_x_v.setChecked(True)
        self.exact_x_v.setAutoRepeat(False)
        self.exact_x_v.setAutoExclusive(False)
        self.exact_x_v.setObjectName(_fromUtf8("exact_x_v"))
        self.exact_t_v = QtGui.QCheckBox(Dialog)
        self.exact_t_v.setGeometry(QtCore.QRect(110, 320, 50, 22))
        self.exact_t_v.setShortcut(_fromUtf8(""))
        self.exact_t_v.setChecked(True)
        self.exact_t_v.setAutoRepeat(False)
        self.exact_t_v.setAutoExclusive(False)
        self.exact_t_v.setObjectName(_fromUtf8("exact_t_v"))
        self.exact_t_x = QtGui.QCheckBox(Dialog)
        self.exact_t_x.setGeometry(QtCore.QRect(110, 290, 50, 22))
        self.exact_t_x.setShortcut(_fromUtf8(""))
        self.exact_t_x.setChecked(True)
        self.exact_t_x.setAutoRepeat(False)
        self.exact_t_x.setAutoExclusive(False)
        self.exact_t_x.setObjectName(_fromUtf8("exact_t_x"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Редактирование констант", None, QtGui.QApplication.UnicodeUTF8))
        self.timelLabel.setText(QtGui.QApplication.translate("Dialog", "Время:", None, QtGui.QApplication.UnicodeUTF8))
        self.timelLabel_2.setText(QtGui.QApplication.translate("Dialog", "Шаг интгр-я:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleYLabel.setText(QtGui.QApplication.translate("Dialog", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleXLabel.setText(QtGui.QApplication.translate("Dialog", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel.setText(QtGui.QApplication.translate("Dialog", "Масштаб:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel_2.setText(QtGui.QApplication.translate("Dialog", "Параметры:", None, QtGui.QApplication.UnicodeUTF8))
        self.mLabel.setText(QtGui.QApplication.translate("Dialog", "m:", None, QtGui.QApplication.UnicodeUTF8))
        self.kLabel.setText(QtGui.QApplication.translate("Dialog", "k:", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("Dialog", "Применить", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("Dialog", "Сброс", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel_3.setText(QtGui.QApplication.translate("Dialog", "Показать сетку:", None, QtGui.QApplication.UnicodeUTF8))
        self.canonical_t_x.setText(QtGui.QApplication.translate("Dialog", "x(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.canonical_t_v.setText(QtGui.QApplication.translate("Dialog", "v(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.canonical_t_dh.setText(QtGui.QApplication.translate("Dialog", "dH(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.eiler_t_dh.setText(QtGui.QApplication.translate("Dialog", "dH(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.eiler_t_x.setText(QtGui.QApplication.translate("Dialog", "x(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.eiler_t_v.setText(QtGui.QApplication.translate("Dialog", "v(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.eiler_x_v.setText(QtGui.QApplication.translate("Dialog", "v(x)", None, QtGui.QApplication.UnicodeUTF8))
        self.canonical_x_v.setText(QtGui.QApplication.translate("Dialog", "v(x)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Канон. метод:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Метод Эйлера:", None, QtGui.QApplication.UnicodeUTF8))
        self.drawTypeGroup.setTitle(QtGui.QApplication.translate("Dialog", "Тип отображения:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineTypeButton.setText(QtGui.QApplication.translate("Dialog", "Линии", None, QtGui.QApplication.UnicodeUTF8))
        self.pointTypeButton.setText(QtGui.QApplication.translate("Dialog", "Точки", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel.setText(QtGui.QApplication.translate("Dialog", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel_2.setText(QtGui.QApplication.translate("Dialog", "v:", None, QtGui.QApplication.UnicodeUTF8))
        self.exact_t_h.setText(QtGui.QApplication.translate("Dialog", "dH(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Точное решение", None, QtGui.QApplication.UnicodeUTF8))
        self.exact_x_v.setText(QtGui.QApplication.translate("Dialog", "v(x)", None, QtGui.QApplication.UnicodeUTF8))
        self.exact_t_v.setText(QtGui.QApplication.translate("Dialog", "v(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.exact_t_x.setText(QtGui.QApplication.translate("Dialog", "x(t)", None, QtGui.QApplication.UnicodeUTF8))

