# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'const_dialog.ui'
#
# Created: Thu May 26 14:01:09 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(732, 318)
        self.resetButton = QtGui.QPushButton(Dialog)
        self.resetButton.setGeometry(QtCore.QRect(110, 270, 85, 27))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.applyButton = QtGui.QPushButton(Dialog)
        self.applyButton.setGeometry(QtCore.QRect(20, 270, 85, 27))
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.gridLayoutWidget_3 = QtGui.QWidget(Dialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 140, 358, 24))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.plotGrid = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.plotGrid.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.plotGrid.setSpacing(2)
        self.plotGrid.setMargin(0)
        self.plotGrid.setObjectName(_fromUtf8("plotGrid"))
        self.t_x = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.t_x.setMaximumSize(QtCore.QSize(53, 16777215))
        self.t_x.setShortcut(_fromUtf8(""))
        self.t_x.setChecked(True)
        self.t_x.setAutoRepeat(False)
        self.t_x.setAutoExclusive(False)
        self.t_x.setObjectName(_fromUtf8("t_x"))
        self.plotGrid.addWidget(self.t_x, 0, 1, 1, 1)
        self.t_v_x = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.t_v_x.setMaximumSize(QtCore.QSize(60, 16777215))
        self.t_v_x.setShortcut(_fromUtf8(""))
        self.t_v_x.setChecked(True)
        self.t_v_x.setAutoRepeat(False)
        self.t_v_x.setAutoExclusive(False)
        self.t_v_x.setObjectName(_fromUtf8("t_v_x"))
        self.plotGrid.addWidget(self.t_v_x, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label.setMaximumSize(QtCore.QSize(72, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.plotGrid.addWidget(self.label, 0, 0, 1, 1)
        self.t_y = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.t_y.setMaximumSize(QtCore.QSize(53, 16777215))
        self.t_y.setShortcut(_fromUtf8(""))
        self.t_y.setChecked(True)
        self.t_y.setAutoRepeat(False)
        self.t_y.setAutoExclusive(False)
        self.t_y.setObjectName(_fromUtf8("t_y"))
        self.plotGrid.addWidget(self.t_y, 0, 2, 1, 1)
        self.liss_x_liss_y = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.liss_x_liss_y.setMaximumSize(QtCore.QSize(53, 16777215))
        self.liss_x_liss_y.setShortcut(_fromUtf8(""))
        self.liss_x_liss_y.setChecked(True)
        self.liss_x_liss_y.setAutoRepeat(False)
        self.liss_x_liss_y.setAutoExclusive(False)
        self.liss_x_liss_y.setObjectName(_fromUtf8("liss_x_liss_y"))
        self.plotGrid.addWidget(self.liss_x_liss_y, 0, 5, 1, 1)
        self.t_v_y = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.t_v_y.setMaximumSize(QtCore.QSize(58, 16777215))
        self.t_v_y.setShortcut(_fromUtf8(""))
        self.t_v_y.setChecked(True)
        self.t_v_y.setAutoRepeat(False)
        self.t_v_y.setAutoExclusive(False)
        self.t_v_y.setObjectName(_fromUtf8("t_v_y"))
        self.plotGrid.addWidget(self.t_v_y, 0, 4, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 220, 151, 23))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.gridShowLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.gridShowLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.gridShowLayout.setMargin(0)
        self.gridShowLayout.setObjectName(_fromUtf8("gridShowLayout"))
        self.scaleLabel_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.scaleLabel_3.setMaximumSize(QtCore.QSize(119, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.scaleLabel_3.setFont(font)
        self.scaleLabel_3.setObjectName(_fromUtf8("scaleLabel_3"))
        self.gridShowLayout.addWidget(self.scaleLabel_3)
        self.showGrid = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.showGrid.setMaximumSize(QtCore.QSize(20, 16777215))
        self.showGrid.setText(_fromUtf8(""))
        self.showGrid.setChecked(True)
        self.showGrid.setObjectName(_fromUtf8("showGrid"))
        self.gridShowLayout.addWidget(self.showGrid)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 180, 297, 24))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.drawTypeGrid = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.drawTypeGrid.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.drawTypeGrid.setMargin(0)
        self.drawTypeGrid.setObjectName(_fromUtf8("drawTypeGrid"))
        self.scaleLabel_4 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.scaleLabel_4.setFont(font)
        self.scaleLabel_4.setObjectName(_fromUtf8("scaleLabel_4"))
        self.drawTypeGrid.addWidget(self.scaleLabel_4)
        self.pointType = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.pointType.setChecked(False)
        self.pointType.setObjectName(_fromUtf8("pointType"))
        self.drawTypeGrid.addWidget(self.pointType)
        self.lineType = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.lineType.setChecked(True)
        self.lineType.setObjectName(_fromUtf8("lineType"))
        self.drawTypeGrid.addWidget(self.lineType)
        self.gridLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 341, 50))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.plotParamGrid = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.plotParamGrid.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.plotParamGrid.setSpacing(2)
        self.plotParamGrid.setMargin(0)
        self.plotParamGrid.setObjectName(_fromUtf8("plotParamGrid"))
        self.kLabel_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.kLabel_5.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.kLabel_5.setFont(font)
        self.kLabel_5.setObjectName(_fromUtf8("kLabel_5"))
        self.plotParamGrid.addWidget(self.kLabel_5, 0, 1, 1, 1)
        self.mLabel_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.mLabel_5.setMaximumSize(QtCore.QSize(60, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.mLabel_5.setFont(font)
        self.mLabel_5.setObjectName(_fromUtf8("mLabel_5"))
        self.plotParamGrid.addWidget(self.mLabel_5, 0, 0, 1, 1)
        self.xLabel_19 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.xLabel_19.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.xLabel_19.setFont(font)
        self.xLabel_19.setObjectName(_fromUtf8("xLabel_19"))
        self.plotParamGrid.addWidget(self.xLabel_19, 0, 2, 1, 1)
        self.xLabel_20 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.xLabel_20.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.xLabel_20.setFont(font)
        self.xLabel_20.setObjectName(_fromUtf8("xLabel_20"))
        self.plotParamGrid.addWidget(self.xLabel_20, 0, 3, 1, 1)
        self.time_limit = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.time_limit.setMaximumSize(QtCore.QSize(65, 16777215))
        self.time_limit.setMinimum(-99999999.0)
        self.time_limit.setMaximum(99999999.0)
        self.time_limit.setSingleStep(0.01)
        self.time_limit.setObjectName(_fromUtf8("time_limit"))
        self.plotParamGrid.addWidget(self.time_limit, 1, 0, 1, 1)
        self.integr_step = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.integr_step.setMaximumSize(QtCore.QSize(72, 16777215))
        self.integr_step.setDecimals(4)
        self.integr_step.setMinimum(-99999999.0)
        self.integr_step.setMaximum(99999999.0)
        self.integr_step.setSingleStep(0.01)
        self.integr_step.setObjectName(_fromUtf8("integr_step"))
        self.plotParamGrid.addWidget(self.integr_step, 1, 1, 1, 1)
        self.scaleX = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.scaleX.setMaximumSize(QtCore.QSize(79, 16777215))
        self.scaleX.setDecimals(5)
        self.scaleX.setMinimum(-99999999.0)
        self.scaleX.setMaximum(99999999.0)
        self.scaleX.setSingleStep(0.01)
        self.scaleX.setProperty(_fromUtf8("value"), 1.0)
        self.scaleX.setObjectName(_fromUtf8("scaleX"))
        self.plotParamGrid.addWidget(self.scaleX, 1, 2, 1, 1)
        self.scaleY = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.scaleY.setMaximumSize(QtCore.QSize(80, 16777215))
        self.scaleY.setDecimals(5)
        self.scaleY.setMinimum(-99999999.0)
        self.scaleY.setMaximum(99999999.0)
        self.scaleY.setSingleStep(0.01)
        self.scaleY.setProperty(_fromUtf8("value"), 1.0)
        self.scaleY.setObjectName(_fromUtf8("scaleY"))
        self.plotParamGrid.addWidget(self.scaleY, 1, 3, 1, 1)
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 80, 551, 50))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.paramsGrid = QtGui.QGridLayout(self.gridLayoutWidget)
        self.paramsGrid.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.paramsGrid.setSpacing(2)
        self.paramsGrid.setMargin(0)
        self.paramsGrid.setObjectName(_fromUtf8("paramsGrid"))
        self.omega_2_x = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.omega_2_x.setMaximumSize(QtCore.QSize(72, 24))
        self.omega_2_x.setDecimals(4)
        self.omega_2_x.setMinimum(-99999999.0)
        self.omega_2_x.setMaximum(99999999.0)
        self.omega_2_x.setSingleStep(0.01)
        self.omega_2_x.setObjectName(_fromUtf8("omega_2_x"))
        self.paramsGrid.addWidget(self.omega_2_x, 1, 1, 1, 1)
        self.xLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.xLabel.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.xLabel.setFont(font)
        self.xLabel.setObjectName(_fromUtf8("xLabel"))
        self.paramsGrid.addWidget(self.xLabel, 0, 1, 1, 1)
        self.mLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.mLabel.setMaximumSize(QtCore.QSize(109, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.mLabel.setFont(font)
        self.mLabel.setObjectName(_fromUtf8("mLabel"))
        self.paramsGrid.addWidget(self.mLabel, 0, 2, 1, 1)
        self.omega_2_y = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.omega_2_y.setMaximumSize(QtCore.QSize(73, 24))
        self.omega_2_y.setDecimals(4)
        self.omega_2_y.setMinimum(-99999999.0)
        self.omega_2_y.setMaximum(99999999.0)
        self.omega_2_y.setSingleStep(0.01)
        self.omega_2_y.setObjectName(_fromUtf8("omega_2_y"))
        self.paramsGrid.addWidget(self.omega_2_y, 1, 2, 1, 1)
        self.v_x = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.v_x.setMaximumSize(QtCore.QSize(122, 24))
        self.v_x.setDecimals(4)
        self.v_x.setMinimum(-99999999.0)
        self.v_x.setMaximum(99999999.0)
        self.v_x.setSingleStep(0.01)
        self.v_x.setObjectName(_fromUtf8("v_x"))
        self.paramsGrid.addWidget(self.v_x, 1, 3, 1, 1)
        self.mLabel_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.mLabel_2.setMaximumSize(QtCore.QSize(119, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.mLabel_2.setFont(font)
        self.mLabel_2.setObjectName(_fromUtf8("mLabel_2"))
        self.paramsGrid.addWidget(self.mLabel_2, 0, 3, 1, 1)
        self.mLabel_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.mLabel_3.setMaximumSize(QtCore.QSize(120, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.mLabel_3.setFont(font)
        self.mLabel_3.setObjectName(_fromUtf8("mLabel_3"))
        self.paramsGrid.addWidget(self.mLabel_3, 0, 4, 1, 1)
        self.v_y = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.v_y.setMaximumSize(QtCore.QSize(122, 24))
        self.v_y.setDecimals(4)
        self.v_y.setMinimum(-99999999.0)
        self.v_y.setMaximum(99999999.0)
        self.v_y.setSingleStep(0.01)
        self.v_y.setObjectName(_fromUtf8("v_y"))
        self.paramsGrid.addWidget(self.v_y, 1, 4, 1, 1)
        self.x = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.x.setMaximumSize(QtCore.QSize(72, 24))
        self.x.setDecimals(4)
        self.x.setMinimum(-99999999.0)
        self.x.setMaximum(99999999.0)
        self.x.setSingleStep(0.01)
        self.x.setObjectName(_fromUtf8("x"))
        self.paramsGrid.addWidget(self.x, 1, 5, 1, 1)
        self.mLabel_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.mLabel_4.setMaximumSize(QtCore.QSize(109, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.mLabel_4.setFont(font)
        self.mLabel_4.setObjectName(_fromUtf8("mLabel_4"))
        self.paramsGrid.addWidget(self.mLabel_4, 0, 5, 1, 1)
        self.y = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.y.setMaximumSize(QtCore.QSize(77, 24))
        self.y.setDecimals(4)
        self.y.setMinimum(-99999999.0)
        self.y.setMaximum(99999999.0)
        self.y.setSingleStep(0.01)
        self.y.setObjectName(_fromUtf8("y"))
        self.paramsGrid.addWidget(self.y, 1, 6, 1, 1)
        self.mLabel_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.mLabel_6.setMaximumSize(QtCore.QSize(118, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.mLabel_6.setFont(font)
        self.mLabel_6.setObjectName(_fromUtf8("mLabel_6"))
        self.paramsGrid.addWidget(self.mLabel_6, 0, 6, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Редактирование констант", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("Dialog", "Сброс", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("Dialog", "Применить", None, QtGui.QApplication.UnicodeUTF8))
        self.t_x.setText(QtGui.QApplication.translate("Dialog", "x(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.t_v_x.setText(QtGui.QApplication.translate("Dialog", "vx(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Графики:", None, QtGui.QApplication.UnicodeUTF8))
        self.t_y.setText(QtGui.QApplication.translate("Dialog", "y(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.liss_x_liss_y.setText(QtGui.QApplication.translate("Dialog", "y(x)", None, QtGui.QApplication.UnicodeUTF8))
        self.t_v_y.setText(QtGui.QApplication.translate("Dialog", "vy(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel_3.setText(QtGui.QApplication.translate("Dialog", "Показать сетку:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel_4.setText(QtGui.QApplication.translate("Dialog", "Тип отображения:", None, QtGui.QApplication.UnicodeUTF8))
        self.pointType.setText(QtGui.QApplication.translate("Dialog", "Точки", None, QtGui.QApplication.UnicodeUTF8))
        self.lineType.setText(QtGui.QApplication.translate("Dialog", "Линии", None, QtGui.QApplication.UnicodeUTF8))
        self.kLabel_5.setText(QtGui.QApplication.translate("Dialog", "Шаг", None, QtGui.QApplication.UnicodeUTF8))
        self.mLabel_5.setText(QtGui.QApplication.translate("Dialog", "Время", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel_19.setText(QtGui.QApplication.translate("Dialog", "Масштаб X", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel_20.setText(QtGui.QApplication.translate("Dialog", "Масштаб Y", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel.setText(QtGui.QApplication.translate("Dialog", "Частота x", None, QtGui.QApplication.UnicodeUTF8))
        self.mLabel.setText(QtGui.QApplication.translate("Dialog", "Частота y", None, QtGui.QApplication.UnicodeUTF8))
        self.mLabel_2.setText(QtGui.QApplication.translate("Dialog", "Начальная скорость x", None, QtGui.QApplication.UnicodeUTF8))
        self.mLabel_3.setText(QtGui.QApplication.translate("Dialog", "Начальная скорость y", None, QtGui.QApplication.UnicodeUTF8))
        self.mLabel_4.setText(QtGui.QApplication.translate("Dialog", "Начальное x", None, QtGui.QApplication.UnicodeUTF8))
        self.mLabel_6.setText(QtGui.QApplication.translate("Dialog", "Начальное y", None, QtGui.QApplication.UnicodeUTF8))

