# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'const_dialog.ui'
#
# Created: Wed May 18 19:16:43 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(726, 335)
        self.resetButton = QtGui.QPushButton(Dialog)
        self.resetButton.setGeometry(QtCore.QRect(110, 290, 85, 27))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.applyButton = QtGui.QPushButton(Dialog)
        self.applyButton.setGeometry(QtCore.QRect(20, 290, 85, 27))
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.gridLayoutWidget_3 = QtGui.QWidget(Dialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 140, 241, 24))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.plotGrid = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.plotGrid.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.plotGrid.setSpacing(2)
        self.plotGrid.setMargin(0)
        self.plotGrid.setObjectName(_fromUtf8("plotGrid"))
        self.canonical_t_x = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.canonical_t_x.setMaximumSize(QtCore.QSize(53, 16777215))
        self.canonical_t_x.setShortcut(_fromUtf8(""))
        self.canonical_t_x.setChecked(True)
        self.canonical_t_x.setAutoRepeat(False)
        self.canonical_t_x.setAutoExclusive(False)
        self.canonical_t_x.setObjectName(_fromUtf8("canonical_t_x"))
        self.plotGrid.addWidget(self.canonical_t_x, 0, 1, 1, 1)
        self.canonical_t_v = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.canonical_t_v.setMaximumSize(QtCore.QSize(51, 16777215))
        self.canonical_t_v.setShortcut(_fromUtf8(""))
        self.canonical_t_v.setChecked(True)
        self.canonical_t_v.setAutoRepeat(False)
        self.canonical_t_v.setAutoExclusive(False)
        self.canonical_t_v.setObjectName(_fromUtf8("canonical_t_v"))
        self.plotGrid.addWidget(self.canonical_t_v, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label.setMaximumSize(QtCore.QSize(72, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.plotGrid.addWidget(self.label, 0, 0, 1, 1)
        self.canonical_x_v = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.canonical_x_v.setMaximumSize(QtCore.QSize(54, 16777215))
        self.canonical_x_v.setShortcut(_fromUtf8(""))
        self.canonical_x_v.setChecked(True)
        self.canonical_x_v.setAutoRepeat(False)
        self.canonical_x_v.setAutoExclusive(False)
        self.canonical_x_v.setObjectName(_fromUtf8("canonical_x_v"))
        self.plotGrid.addWidget(self.canonical_x_v, 0, 2, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 220, 151, 23))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.gridShowLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.gridShowLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.gridShowLayout.setMargin(0)
        self.gridShowLayout.setObjectName(_fromUtf8("gridShowLayout"))
        self.scaleLabel_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.scaleLabel_3.setMaximumSize(QtCore.QSize(119, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.scaleLabel_3.setFont(font)
        self.scaleLabel_3.setObjectName(_fromUtf8("scaleLabel_3"))
        self.gridShowLayout.addWidget(self.scaleLabel_3)
        self.showGrid = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.showGrid.setMaximumSize(QtCore.QSize(20, 16777215))
        self.showGrid.setText(_fromUtf8(""))
        self.showGrid.setChecked(True)
        self.showGrid.setObjectName(_fromUtf8("showGrid"))
        self.gridShowLayout.addWidget(self.showGrid)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 180, 297, 24))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.drawTypeGrid = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.drawTypeGrid.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.drawTypeGrid.setMargin(0)
        self.drawTypeGrid.setObjectName(_fromUtf8("drawTypeGrid"))
        self.scaleLabel_4 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.scaleLabel_4.setFont(font)
        self.scaleLabel_4.setObjectName(_fromUtf8("scaleLabel_4"))
        self.drawTypeGrid.addWidget(self.scaleLabel_4)
        self.pointType = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.pointType.setChecked(False)
        self.pointType.setObjectName(_fromUtf8("pointType"))
        self.drawTypeGrid.addWidget(self.pointType)
        self.lineType = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.lineType.setChecked(True)
        self.lineType.setObjectName(_fromUtf8("lineType"))
        self.drawTypeGrid.addWidget(self.lineType)
        self.gridLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 341, 50))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.plotParamGrid = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.plotParamGrid.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.plotParamGrid.setSpacing(2)
        self.plotParamGrid.setMargin(0)
        self.plotParamGrid.setObjectName(_fromUtf8("plotParamGrid"))
        self.kLabel_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.kLabel_5.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.kLabel_5.setFont(font)
        self.kLabel_5.setObjectName(_fromUtf8("kLabel_5"))
        self.plotParamGrid.addWidget(self.kLabel_5, 0, 1, 1, 1)
        self.mLabel_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.mLabel_5.setMaximumSize(QtCore.QSize(60, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.mLabel_5.setFont(font)
        self.mLabel_5.setObjectName(_fromUtf8("mLabel_5"))
        self.plotParamGrid.addWidget(self.mLabel_5, 0, 0, 1, 1)
        self.xLabel_19 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.xLabel_19.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.xLabel_19.setFont(font)
        self.xLabel_19.setObjectName(_fromUtf8("xLabel_19"))
        self.plotParamGrid.addWidget(self.xLabel_19, 0, 2, 1, 1)
        self.xLabel_20 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.xLabel_20.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.xLabel_20.setFont(font)
        self.xLabel_20.setObjectName(_fromUtf8("xLabel_20"))
        self.plotParamGrid.addWidget(self.xLabel_20, 0, 3, 1, 1)
        self.time_limit = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.time_limit.setMaximumSize(QtCore.QSize(65, 16777215))
        self.time_limit.setMinimum(-99999999.0)
        self.time_limit.setMaximum(99999999.0)
        self.time_limit.setSingleStep(0.01)
        self.time_limit.setObjectName(_fromUtf8("time_limit"))
        self.plotParamGrid.addWidget(self.time_limit, 1, 0, 1, 1)
        self.integr_step = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.integr_step.setMaximumSize(QtCore.QSize(72, 16777215))
        self.integr_step.setDecimals(4)
        self.integr_step.setMinimum(-99999999.0)
        self.integr_step.setMaximum(99999999.0)
        self.integr_step.setSingleStep(0.01)
        self.integr_step.setObjectName(_fromUtf8("integr_step"))
        self.plotParamGrid.addWidget(self.integr_step, 1, 1, 1, 1)
        self.scaleX = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.scaleX.setMaximumSize(QtCore.QSize(79, 16777215))
        self.scaleX.setDecimals(5)
        self.scaleX.setMinimum(-99999999.0)
        self.scaleX.setMaximum(99999999.0)
        self.scaleX.setSingleStep(0.01)
        self.scaleX.setProperty(_fromUtf8("value"), 1.0)
        self.scaleX.setObjectName(_fromUtf8("scaleX"))
        self.plotParamGrid.addWidget(self.scaleX, 1, 2, 1, 1)
        self.scaleY = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.scaleY.setMaximumSize(QtCore.QSize(80, 16777215))
        self.scaleY.setDecimals(5)
        self.scaleY.setMinimum(-99999999.0)
        self.scaleY.setMaximum(99999999.0)
        self.scaleY.setSingleStep(0.01)
        self.scaleY.setProperty(_fromUtf8("value"), 1.0)
        self.scaleY.setObjectName(_fromUtf8("scaleY"))
        self.plotParamGrid.addWidget(self.scaleY, 1, 3, 1, 1)
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 80, 686, 50))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.paramsGrid = QtGui.QGridLayout(self.gridLayoutWidget)
        self.paramsGrid.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.paramsGrid.setSpacing(2)
        self.paramsGrid.setMargin(0)
        self.paramsGrid.setObjectName(_fromUtf8("paramsGrid"))
        self.m = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.m.setMaximumSize(QtCore.QSize(76, 24))
        self.m.setDecimals(4)
        self.m.setMinimum(-99999999.0)
        self.m.setMaximum(99999999.0)
        self.m.setSingleStep(0.01)
        self.m.setObjectName(_fromUtf8("m"))
        self.paramsGrid.addWidget(self.m, 1, 0, 1, 1)
        self.k = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.k.setMaximumSize(QtCore.QSize(75, 24))
        self.k.setDecimals(4)
        self.k.setMinimum(-99999999.0)
        self.k.setMaximum(99999999.0)
        self.k.setSingleStep(0.01)
        self.k.setObjectName(_fromUtf8("k"))
        self.paramsGrid.addWidget(self.k, 1, 1, 1, 1)
        self.kLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.kLabel.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.kLabel.setFont(font)
        self.kLabel.setObjectName(_fromUtf8("kLabel"))
        self.paramsGrid.addWidget(self.kLabel, 0, 1, 1, 1)
        self.x = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.x.setMaximumSize(QtCore.QSize(136, 24))
        self.x.setDecimals(4)
        self.x.setMinimum(-99999999.0)
        self.x.setMaximum(99999999.0)
        self.x.setSingleStep(0.01)
        self.x.setObjectName(_fromUtf8("x"))
        self.paramsGrid.addWidget(self.x, 1, 5, 1, 1)
        self.xLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.xLabel.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.xLabel.setFont(font)
        self.xLabel.setObjectName(_fromUtf8("xLabel"))
        self.paramsGrid.addWidget(self.xLabel, 0, 5, 1, 1)
        self.xLabel_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.xLabel_2.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.xLabel_2.setFont(font)
        self.xLabel_2.setObjectName(_fromUtf8("xLabel_2"))
        self.paramsGrid.addWidget(self.xLabel_2, 0, 6, 1, 1)
        self.v = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.v.setMaximumSize(QtCore.QSize(122, 24))
        self.v.setDecimals(4)
        self.v.setMinimum(-99999999.0)
        self.v.setMaximum(99999999.0)
        self.v.setSingleStep(0.01)
        self.v.setObjectName(_fromUtf8("v"))
        self.paramsGrid.addWidget(self.v, 1, 6, 1, 1)
        self.mLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.mLabel.setMaximumSize(QtCore.QSize(60, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.mLabel.setFont(font)
        self.mLabel.setObjectName(_fromUtf8("mLabel"))
        self.paramsGrid.addWidget(self.mLabel, 0, 0, 1, 1)
        self.xLabel_15 = QtGui.QLabel(self.gridLayoutWidget)
        self.xLabel_15.setMaximumSize(QtCore.QSize(163, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.xLabel_15.setFont(font)
        self.xLabel_15.setObjectName(_fromUtf8("xLabel_15"))
        self.paramsGrid.addWidget(self.xLabel_15, 0, 2, 1, 1)
        self.xLabel_16 = QtGui.QLabel(self.gridLayoutWidget)
        self.xLabel_16.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.xLabel_16.setFont(font)
        self.xLabel_16.setObjectName(_fromUtf8("xLabel_16"))
        self.paramsGrid.addWidget(self.xLabel_16, 0, 3, 1, 1)
        self.resist_koef = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.resist_koef.setMaximumSize(QtCore.QSize(89, 24))
        self.resist_koef.setDecimals(4)
        self.resist_koef.setMinimum(-99999999.0)
        self.resist_koef.setMaximum(99999999.0)
        self.resist_koef.setSingleStep(0.01)
        self.resist_koef.setObjectName(_fromUtf8("resist_koef"))
        self.paramsGrid.addWidget(self.resist_koef, 1, 2, 1, 1)
        self.f = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.f.setMaximumSize(QtCore.QSize(88, 24))
        self.f.setDecimals(4)
        self.f.setMinimum(-99999999.0)
        self.f.setMaximum(99999999.0)
        self.f.setSingleStep(0.01)
        self.f.setObjectName(_fromUtf8("f"))
        self.paramsGrid.addWidget(self.f, 1, 3, 1, 1)
        self.xLabel_17 = QtGui.QLabel(self.gridLayoutWidget)
        self.xLabel_17.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.xLabel_17.setFont(font)
        self.xLabel_17.setObjectName(_fromUtf8("xLabel_17"))
        self.paramsGrid.addWidget(self.xLabel_17, 0, 4, 1, 1)
        self.f_omega = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.f_omega.setMaximumSize(QtCore.QSize(88, 24))
        self.f_omega.setDecimals(4)
        self.f_omega.setMinimum(-99999999.0)
        self.f_omega.setMaximum(99999999.0)
        self.f_omega.setSingleStep(0.01)
        self.f_omega.setObjectName(_fromUtf8("f_omega"))
        self.paramsGrid.addWidget(self.f_omega, 1, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Редактирование констант", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("Dialog", "Сброс", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("Dialog", "Применить", None, QtGui.QApplication.UnicodeUTF8))
        self.canonical_t_x.setText(QtGui.QApplication.translate("Dialog", "x(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.canonical_t_v.setText(QtGui.QApplication.translate("Dialog", "v(t)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Графики:", None, QtGui.QApplication.UnicodeUTF8))
        self.canonical_x_v.setText(QtGui.QApplication.translate("Dialog", "v(x)", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel_3.setText(QtGui.QApplication.translate("Dialog", "Показать сетку:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel_4.setText(QtGui.QApplication.translate("Dialog", "Тип отображения:", None, QtGui.QApplication.UnicodeUTF8))
        self.pointType.setText(QtGui.QApplication.translate("Dialog", "Точки", None, QtGui.QApplication.UnicodeUTF8))
        self.lineType.setText(QtGui.QApplication.translate("Dialog", "Линии", None, QtGui.QApplication.UnicodeUTF8))
        self.kLabel_5.setText(QtGui.QApplication.translate("Dialog", "Шаг", None, QtGui.QApplication.UnicodeUTF8))
        self.mLabel_5.setText(QtGui.QApplication.translate("Dialog", "Время", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel_19.setText(QtGui.QApplication.translate("Dialog", "Масштаб X", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel_20.setText(QtGui.QApplication.translate("Dialog", "Масштаб Y", None, QtGui.QApplication.UnicodeUTF8))
        self.kLabel.setText(QtGui.QApplication.translate("Dialog", "Жесткость", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel.setText(QtGui.QApplication.translate("Dialog", "Начальное положение", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel_2.setText(QtGui.QApplication.translate("Dialog", "Начальная скорость", None, QtGui.QApplication.UnicodeUTF8))
        self.mLabel.setText(QtGui.QApplication.translate("Dialog", "Массса", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel_15.setText(QtGui.QApplication.translate("Dialog", "Сопрот. среды", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel_16.setText(QtGui.QApplication.translate("Dialog", "Внешняя сила", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel_17.setText(QtGui.QApplication.translate("Dialog", "Частота силы", None, QtGui.QApplication.UnicodeUTF8))

