# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Thu Apr  7 11:19:28 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(914, 561)
        self.centralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 911, 531))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.plotArea = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.plotArea.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.plotArea.setMargin(0)
        self.plotArea.setObjectName(_fromUtf8("plotArea"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.editMenu = QtGui.QMenu(self.menubar)
        self.editMenu.setObjectName(_fromUtf8("editMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.saveImageAction = QtGui.QAction(MainWindow)
        self.saveImageAction.setObjectName(_fromUtf8("saveImageAction"))
        self.exitAction = QtGui.QAction(MainWindow)
        self.exitAction.setObjectName(_fromUtf8("exitAction"))
        self.scaleEdit = QtGui.QAction(MainWindow)
        self.scaleEdit.setObjectName(_fromUtf8("scaleEdit"))
        self.constEdit = QtGui.QAction(MainWindow)
        self.constEdit.setObjectName(_fromUtf8("constEdit"))
        self.astroidAction = QtGui.QAction(MainWindow)
        self.astroidAction.setObjectName(_fromUtf8("astroidAction"))
        self.circleAction = QtGui.QAction(MainWindow)
        self.circleAction.setObjectName(_fromUtf8("circleAction"))
        self.cardioidAction = QtGui.QAction(MainWindow)
        self.cardioidAction.setObjectName(_fromUtf8("cardioidAction"))
        self.evolventAction = QtGui.QAction(MainWindow)
        self.evolventAction.setObjectName(_fromUtf8("evolventAction"))
        self.verAnAction = QtGui.QAction(MainWindow)
        self.verAnAction.setObjectName(_fromUtf8("verAnAction"))
        self.jeronLeminiskatAction = QtGui.QAction(MainWindow)
        self.jeronLeminiskatAction.setObjectName(_fromUtf8("jeronLeminiskatAction"))
        self.bernLeminiskateAction = QtGui.QAction(MainWindow)
        self.bernLeminiskateAction.setObjectName(_fromUtf8("bernLeminiskateAction"))
        self.deltoidAction = QtGui.QAction(MainWindow)
        self.deltoidAction.setObjectName(_fromUtf8("deltoidAction"))
        self.logSpiralAction = QtGui.QAction(MainWindow)
        self.logSpiralAction.setObjectName(_fromUtf8("logSpiralAction"))
        self.hypocycloidAction = QtGui.QAction(MainWindow)
        self.hypocycloidAction.setObjectName(_fromUtf8("hypocycloidAction"))
        self.trohoidAction = QtGui.QAction(MainWindow)
        self.trohoidAction.setObjectName(_fromUtf8("trohoidAction"))
        self.epicycloidAction = QtGui.QAction(MainWindow)
        self.epicycloidAction.setObjectName(_fromUtf8("epicycloidAction"))
        self.epitrohoidAction = QtGui.QAction(MainWindow)
        self.epitrohoidAction.setObjectName(_fromUtf8("epitrohoidAction"))
        self.nefroidAction = QtGui.QAction(MainWindow)
        self.nefroidAction.setObjectName(_fromUtf8("nefroidAction"))
        self.hypotrohoidAction = QtGui.QAction(MainWindow)
        self.hypotrohoidAction.setObjectName(_fromUtf8("hypotrohoidAction"))
        self.cardioidAction_2 = QtGui.QAction(MainWindow)
        self.cardioidAction_2.setObjectName(_fromUtf8("cardioidAction_2"))
        self.pascalSnailAction = QtGui.QAction(MainWindow)
        self.pascalSnailAction.setObjectName(_fromUtf8("pascalSnailAction"))
        self.reducedEpitrohoidAction = QtGui.QAction(MainWindow)
        self.reducedEpitrohoidAction.setObjectName(_fromUtf8("reducedEpitrohoidAction"))
        self.roseAction = QtGui.QAction(MainWindow)
        self.roseAction.setObjectName(_fromUtf8("roseAction"))
        self.constEditAction = QtGui.QAction(MainWindow)
        self.constEditAction.setObjectName(_fromUtf8("constEditAction"))
        self.calculateAction = QtGui.QAction(MainWindow)
        self.calculateAction.setObjectName(_fromUtf8("calculateAction"))
        self.editMenu.addAction(self.calculateAction)
        self.editMenu.addAction(self.constEditAction)
        self.menubar.addAction(self.editMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.exitAction, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Осциллятор", None, QtGui.QApplication.UnicodeUTF8))
        self.editMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Правка", None, QtGui.QApplication.UnicodeUTF8))
        self.saveImageAction.setText(QtGui.QApplication.translate("MainWindow", "Сохранить изображение...", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setText(QtGui.QApplication.translate("MainWindow", "Выход", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleEdit.setText(QtGui.QApplication.translate("MainWindow", "Масштаб...", None, QtGui.QApplication.UnicodeUTF8))
        self.constEdit.setText(QtGui.QApplication.translate("MainWindow", "Константы...", None, QtGui.QApplication.UnicodeUTF8))
        self.astroidAction.setText(QtGui.QApplication.translate("MainWindow", "Астроида", None, QtGui.QApplication.UnicodeUTF8))
        self.circleAction.setText(QtGui.QApplication.translate("MainWindow", "Окружность", None, QtGui.QApplication.UnicodeUTF8))
        self.cardioidAction.setText(QtGui.QApplication.translate("MainWindow", "Кардиоида", None, QtGui.QApplication.UnicodeUTF8))
        self.evolventAction.setText(QtGui.QApplication.translate("MainWindow", "Эвольвента", None, QtGui.QApplication.UnicodeUTF8))
        self.verAnAction.setText(QtGui.QApplication.translate("MainWindow", "Верзьера Аньези", None, QtGui.QApplication.UnicodeUTF8))
        self.jeronLeminiskatAction.setText(QtGui.QApplication.translate("MainWindow", "Лемниската Жероно", None, QtGui.QApplication.UnicodeUTF8))
        self.bernLeminiskateAction.setText(QtGui.QApplication.translate("MainWindow", "Лемниската Бернулли", None, QtGui.QApplication.UnicodeUTF8))
        self.deltoidAction.setText(QtGui.QApplication.translate("MainWindow", "Дельтоида", None, QtGui.QApplication.UnicodeUTF8))
        self.logSpiralAction.setText(QtGui.QApplication.translate("MainWindow", "Логарифмическая спираль", None, QtGui.QApplication.UnicodeUTF8))
        self.hypocycloidAction.setText(QtGui.QApplication.translate("MainWindow", "Гипоциклоида", None, QtGui.QApplication.UnicodeUTF8))
        self.trohoidAction.setText(QtGui.QApplication.translate("MainWindow", "Трохоида", None, QtGui.QApplication.UnicodeUTF8))
        self.epicycloidAction.setText(QtGui.QApplication.translate("MainWindow", "Эпициклоида", None, QtGui.QApplication.UnicodeUTF8))
        self.epitrohoidAction.setText(QtGui.QApplication.translate("MainWindow", "Эпитрохоида", None, QtGui.QApplication.UnicodeUTF8))
        self.nefroidAction.setText(QtGui.QApplication.translate("MainWindow", "Нефроида", None, QtGui.QApplication.UnicodeUTF8))
        self.hypotrohoidAction.setText(QtGui.QApplication.translate("MainWindow", "Гипотрохоида", None, QtGui.QApplication.UnicodeUTF8))
        self.cardioidAction_2.setText(QtGui.QApplication.translate("MainWindow", "Кардиоида", None, QtGui.QApplication.UnicodeUTF8))
        self.pascalSnailAction.setText(QtGui.QApplication.translate("MainWindow", "Улитка Паскаля", None, QtGui.QApplication.UnicodeUTF8))
        self.reducedEpitrohoidAction.setText(QtGui.QApplication.translate("MainWindow", "Укороченая эпитрохоида", None, QtGui.QApplication.UnicodeUTF8))
        self.roseAction.setText(QtGui.QApplication.translate("MainWindow", "Роза", None, QtGui.QApplication.UnicodeUTF8))
        self.constEditAction.setText(QtGui.QApplication.translate("MainWindow", "Константы...", None, QtGui.QApplication.UnicodeUTF8))
        self.calculateAction.setText(QtGui.QApplication.translate("MainWindow", "Просчитать и отобразить", None, QtGui.QApplication.UnicodeUTF8))

