# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Thu Mar 24 23:39:21 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 561)
        self.centralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 911, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plotArea = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.plotArea.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.plotArea.setObjectName("plotArea")
        self.toolBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.toolBox.setTitle("")
        self.toolBox.setObjectName("toolBox")
        self.scaleReset = QtGui.QPushButton(self.toolBox)
        self.scaleReset.setGeometry(QtCore.QRect(360, 5, 70, 20))
        self.scaleReset.setObjectName("scaleReset")
        self.scaleLabel = QtGui.QLabel(self.toolBox)
        self.scaleLabel.setGeometry(QtCore.QRect(11, 6, 60, 15))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.scaleLabel.setFont(font)
        self.scaleLabel.setObjectName("scaleLabel")
        self.scaleXLabel = QtGui.QLabel(self.toolBox)
        self.scaleXLabel.setGeometry(QtCore.QRect(80, 7, 16, 16))
        self.scaleXLabel.setObjectName("scaleXLabel")
        self.scaleYLabel = QtGui.QLabel(self.toolBox)
        self.scaleYLabel.setGeometry(QtCore.QRect(178, 7, 16, 16))
        self.scaleYLabel.setObjectName("scaleYLabel")
        self.intervalLabel = QtGui.QLabel(self.toolBox)
        self.intervalLabel.setGeometry(QtCore.QRect(494, 6, 130, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.intervalLabel.setFont(font)
        self.intervalLabel.setObjectName("intervalLabel")
        self.intervalMin = QtGui.QDoubleSpinBox(self.toolBox)
        self.intervalMin.setGeometry(QtCore.QRect(630, 5, 70, 20))
        self.intervalMin.setMinimum(-99999999.0)
        self.intervalMin.setMaximum(99999999.0)
        self.intervalMin.setSingleStep(0.01)
        self.intervalMin.setObjectName("intervalMin")
        self.intervalMax = QtGui.QDoubleSpinBox(self.toolBox)
        self.intervalMax.setGeometry(QtCore.QRect(704, 5, 70, 20))
        self.intervalMax.setMinimum(-99999999.0)
        self.intervalMax.setMaximum(99999999.0)
        self.intervalMax.setSingleStep(0.01)
        self.intervalMax.setObjectName("intervalMax")
        self.intervalOk = QtGui.QPushButton(self.toolBox)
        self.intervalOk.setGeometry(QtCore.QRect(780, 5, 81, 20))
        self.intervalOk.setObjectName("intervalOk")
        self.scaleX = QtGui.QDoubleSpinBox(self.toolBox)
        self.scaleX.setGeometry(QtCore.QRect(93, 5, 80, 20))
        self.scaleX.setDecimals(5)
        self.scaleX.setMinimum(-99999999.0)
        self.scaleX.setMaximum(99999999.0)
        self.scaleX.setSingleStep(0.01)
        self.scaleX.setProperty("value", 1.0)
        self.scaleX.setObjectName("scaleX")
        self.scaleY = QtGui.QDoubleSpinBox(self.toolBox)
        self.scaleY.setGeometry(QtCore.QRect(191, 5, 80, 20))
        self.scaleY.setDecimals(5)
        self.scaleY.setMinimum(-99999999.0)
        self.scaleY.setMaximum(99999999.0)
        self.scaleY.setSingleStep(0.01)
        self.scaleY.setProperty("value", 1.0)
        self.scaleY.setObjectName("scaleY")
        self.scaleApply = QtGui.QPushButton(self.toolBox)
        self.scaleApply.setGeometry(QtCore.QRect(279, 5, 80, 20))
        self.scaleApply.setObjectName("scaleApply")
        self.plotArea.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 25))
        self.menubar.setObjectName("menubar")
        self.curivesMenu = QtGui.QMenu(self.menubar)
        self.curivesMenu.setObjectName("curivesMenu")
        MainWindow.setMenuBar(self.menubar)
        self.saveImageAction = QtGui.QAction(MainWindow)
        self.saveImageAction.setObjectName("saveImageAction")
        self.exitAction = QtGui.QAction(MainWindow)
        self.exitAction.setObjectName("exitAction")
        self.scaleEdit = QtGui.QAction(MainWindow)
        self.scaleEdit.setObjectName("scaleEdit")
        self.constEdit = QtGui.QAction(MainWindow)
        self.constEdit.setObjectName("constEdit")
        self.astroidAction = QtGui.QAction(MainWindow)
        self.astroidAction.setObjectName("astroidAction")
        self.circleAction = QtGui.QAction(MainWindow)
        self.circleAction.setObjectName("circleAction")
        self.cardioidAction = QtGui.QAction(MainWindow)
        self.cardioidAction.setObjectName("cardioidAction")
        self.evolventAction = QtGui.QAction(MainWindow)
        self.evolventAction.setObjectName("evolventAction")
        self.verAnAction = QtGui.QAction(MainWindow)
        self.verAnAction.setObjectName("verAnAction")
        self.jeronLeminiskatAction = QtGui.QAction(MainWindow)
        self.jeronLeminiskatAction.setObjectName("jeronLeminiskatAction")
        self.bernLeminiskateAction = QtGui.QAction(MainWindow)
        self.bernLeminiskateAction.setObjectName("bernLeminiskateAction")
        self.deltoidAction = QtGui.QAction(MainWindow)
        self.deltoidAction.setObjectName("deltoidAction")
        self.logSpiralAction = QtGui.QAction(MainWindow)
        self.logSpiralAction.setObjectName("logSpiralAction")
        self.hypocycloidAction = QtGui.QAction(MainWindow)
        self.hypocycloidAction.setObjectName("hypocycloidAction")
        self.trohoidAction = QtGui.QAction(MainWindow)
        self.trohoidAction.setObjectName("trohoidAction")
        self.epicycloidAction = QtGui.QAction(MainWindow)
        self.epicycloidAction.setObjectName("epicycloidAction")
        self.epitrohoidAction = QtGui.QAction(MainWindow)
        self.epitrohoidAction.setObjectName("epitrohoidAction")
        self.nefroidAction = QtGui.QAction(MainWindow)
        self.nefroidAction.setObjectName("nefroidAction")
        self.hypotrohoidAction = QtGui.QAction(MainWindow)
        self.hypotrohoidAction.setObjectName("hypotrohoidAction")
        self.cardioidAction_2 = QtGui.QAction(MainWindow)
        self.cardioidAction_2.setObjectName("cardioidAction_2")
        self.pascalSnailAction = QtGui.QAction(MainWindow)
        self.pascalSnailAction.setObjectName("pascalSnailAction")
        self.reducedEpitrohoidAction = QtGui.QAction(MainWindow)
        self.reducedEpitrohoidAction.setObjectName("reducedEpitrohoidAction")
        self.roseAction = QtGui.QAction(MainWindow)
        self.roseAction.setObjectName("roseAction")
        self.curivesMenu.addAction(self.astroidAction)
        self.curivesMenu.addAction(self.hypocycloidAction)
        self.curivesMenu.addAction(self.deltoidAction)
        self.curivesMenu.addAction(self.bernLeminiskateAction)
        self.curivesMenu.addAction(self.jeronLeminiskatAction)
        self.curivesMenu.addAction(self.logSpiralAction)
        self.curivesMenu.addAction(self.circleAction)
        self.curivesMenu.addAction(self.trohoidAction)
        self.curivesMenu.addAction(self.epitrohoidAction)
        self.curivesMenu.addAction(self.reducedEpitrohoidAction)
        self.curivesMenu.addAction(self.pascalSnailAction)
        self.curivesMenu.addAction(self.evolventAction)
        self.curivesMenu.addAction(self.nefroidAction)
        self.curivesMenu.addAction(self.cardioidAction)
        self.curivesMenu.addAction(self.epicycloidAction)
        self.menubar.addAction(self.curivesMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.exitAction, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Спирограф", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleReset.setText(QtGui.QApplication.translate("MainWindow", "Сбросить", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel.setText(QtGui.QApplication.translate("MainWindow", "Масштаб:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleXLabel.setText(QtGui.QApplication.translate("MainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleYLabel.setText(QtGui.QApplication.translate("MainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.intervalLabel.setText(QtGui.QApplication.translate("MainWindow", "Интервал аргумента:", None, QtGui.QApplication.UnicodeUTF8))
        self.intervalOk.setText(QtGui.QApplication.translate("MainWindow", "Применить", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleApply.setText(QtGui.QApplication.translate("MainWindow", "Применить", None, QtGui.QApplication.UnicodeUTF8))
        self.curivesMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Кривые", None, QtGui.QApplication.UnicodeUTF8))
        self.saveImageAction.setText(QtGui.QApplication.translate("MainWindow", "Сохранить изображение...", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setText(QtGui.QApplication.translate("MainWindow", "Выход", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleEdit.setText(QtGui.QApplication.translate("MainWindow", "Масштаб...", None, QtGui.QApplication.UnicodeUTF8))
        self.constEdit.setText(QtGui.QApplication.translate("MainWindow", "Константы...", None, QtGui.QApplication.UnicodeUTF8))
        self.astroidAction.setText(QtGui.QApplication.translate("MainWindow", "Астроида", None, QtGui.QApplication.UnicodeUTF8))
        self.circleAction.setText(QtGui.QApplication.translate("MainWindow", "Окружность", None, QtGui.QApplication.UnicodeUTF8))
        self.cardioidAction.setText(QtGui.QApplication.translate("MainWindow", "Кардиоида", None, QtGui.QApplication.UnicodeUTF8))
        self.evolventAction.setText(QtGui.QApplication.translate("MainWindow", "Эвольвента", None, QtGui.QApplication.UnicodeUTF8))
        self.verAnAction.setText(QtGui.QApplication.translate("MainWindow", "Верзьера Аньези", None, QtGui.QApplication.UnicodeUTF8))
        self.jeronLeminiskatAction.setText(QtGui.QApplication.translate("MainWindow", "Лемниската Жероно", None, QtGui.QApplication.UnicodeUTF8))
        self.bernLeminiskateAction.setText(QtGui.QApplication.translate("MainWindow", "Лемниската Бернулли", None, QtGui.QApplication.UnicodeUTF8))
        self.deltoidAction.setText(QtGui.QApplication.translate("MainWindow", "Дельтоида", None, QtGui.QApplication.UnicodeUTF8))
        self.logSpiralAction.setText(QtGui.QApplication.translate("MainWindow", "Логарифмическая спираль", None, QtGui.QApplication.UnicodeUTF8))
        self.hypocycloidAction.setText(QtGui.QApplication.translate("MainWindow", "Гипоциклоида", None, QtGui.QApplication.UnicodeUTF8))
        self.trohoidAction.setText(QtGui.QApplication.translate("MainWindow", "Трохоида", None, QtGui.QApplication.UnicodeUTF8))
        self.epicycloidAction.setText(QtGui.QApplication.translate("MainWindow", "Эпициклоида", None, QtGui.QApplication.UnicodeUTF8))
        self.epitrohoidAction.setText(QtGui.QApplication.translate("MainWindow", "Эпитрохоида", None, QtGui.QApplication.UnicodeUTF8))
        self.nefroidAction.setText(QtGui.QApplication.translate("MainWindow", "Нефроида", None, QtGui.QApplication.UnicodeUTF8))
        self.hypotrohoidAction.setText(QtGui.QApplication.translate("MainWindow", "Гипотрохоида", None, QtGui.QApplication.UnicodeUTF8))
        self.cardioidAction_2.setText(QtGui.QApplication.translate("MainWindow", "Кардиоида", None, QtGui.QApplication.UnicodeUTF8))
        self.pascalSnailAction.setText(QtGui.QApplication.translate("MainWindow", "Улитка Паскаля", None, QtGui.QApplication.UnicodeUTF8))
        self.reducedEpitrohoidAction.setText(QtGui.QApplication.translate("MainWindow", "Укороченая эпитрохоида", None, QtGui.QApplication.UnicodeUTF8))
        self.roseAction.setText(QtGui.QApplication.translate("MainWindow", "Роза", None, QtGui.QApplication.UnicodeUTF8))

